services:
  mysql:
    image: mysql:8.4
    container_name: mysql_srv
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: opiniones
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/data:/var/lib/mysql
    networks:
      - services_net
    ports:
      - "3316:3306"

  mongodb:
    image: mongo:7
    container_name: mongo_srv
    restart: always
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js
      - ./mongo/data:/data/db

    ports:
      - "27017:27017"
    networks:
      - services_net

  api:
    build: ./api
    container_name: api_srv
    restart: always
    depends_on:
      - mysql
      - mongodb
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: opiniones
      MONGO_URI: mongodb://mongodb:27017/opiniones
    ports:
      - "3000:3000"
    volumes:      
      - ./api:/usr/src/app  # Mounts the API source code
      # - ./api/node_modules:/usr/src/app/node_modules
      - /usr/src/app/node_modules  # Prevents overwriting node_modules

    command: ["npm", "run", "dev"]
    networks:
      - services_net

  web:
    image: php:8.3-apache
    container_name: web_srv
    restart: always
    depends_on:
      - api
    volumes:
      - ./web:/var/www/html
    ports:
      - "8180:80"
    networks:
      - services_net

networks:
  services_net:
    driver: bridge
